### ISSUE TITLE
PostgreSQL engineId `postgresql/13.2` is not valid

### ISSUE THREAD

**Issue by nagyv** [linode/provider-linode#9]
I have the following resource definition:

```yaml
apiVersion: database.linode.upbound.io/v1alpha1
kind: PostgreSQL
metadata:
  name: my-db
spec: 
  forProvider:
    region: eu-central
    engineId: postgresql/13.2
    type: g6-nanode-1
    label: my-db
  providerConfigRef:
    name: linode-config
```

The cluster claims that the `engine` is not valid: "apply failed: failed to create postgresql database: [400] [engine] engine is not valid:"

I don't have `engine` specified, but it does not seem to be a valid property according to the docs and the examples.

I run `xpkg.upbound.io/linode/provider-linode:v0.0.7`
